### ISSUE TITLE
Support for user specific header

### ISSUE THREAD

**Issue by chrboe** [jbaublitz/neli#106]
Generic netlink supports a "user specific message header" between the genlmsghdr and the payload:

```
   0                   1                   2                   3
   0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
  +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
  |                Netlink message header (nlmsghdr)              |
  +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
  |           Generic Netlink message header (genlmsghdr)         |
  +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
  |             Optional user specific message header             |
  +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
  |           Optional Generic Netlink message payload            |
  +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```
(source: https://lwn.net/Articles/208755/)

Am I missing something or does neli not support writing to this header? I couldn't find any hints to it in the code or documentation.

**Comment by jbaublitz** [comment]
Hi @chrboe, thanks for the report! While I am relatively familiar with netlink at this point, most of that information comes from the documentation in the header files and the sub-protocols I've personally interacted with. As a result, there are occasionally features that I miss. I'm happy to add in support for this though. Because I really don't want to break compatibility for users using the 0.5.x branch and the 0.6.0 release is not ready, how would you feel about a new release on the 0.5.x branch with a separate `Genlmsghdr` structure that does support the user header? I'll remove the legacy struct in the 0.6.0 release but this should allow you to use my library in the 0.5.x releases too. Is that something you'd be interested in? The next few days are going to be quite busy for me but I should be able to start working on it within 3 days or so. I'll also put up a PR and tag you in it so you can give your thoughts on the design as I progress. Thanks again for the report! I'm always happy to take feedback and make my library better!

**Comment by chrboe** [comment]
That sounds great, thanks :slightly_smiling_face: 

I'll be happy to review and test any progress :+1:

**Comment by jbaublitz** [comment]
Hi @chrboe, I was on vacation for the past two weeks, but I'm going to start looking into this in the next week or so!

**Comment by jbaublitz** [comment]
@chrboe Now that the most recent bug fix release is out, I'm circling back to this. I did have one question before I begin: is there an indication for parsing that the user-specific header is present? This is part of the problem with netlink: parsing seems to rely pretty heavily on stateful parsing in some cases and simply the client knowing what is being sent back to it in others. I'd like to find a generic way to detect whether the user-specific header is present or not. If I can't do that, I'm going to make the field typed as a generic like this:

```rust
pub struct UserHeader<H>(H);

pub struct NoUserHeader;

/// Struct representing generic netlink header and payload
#[derive(Debug, PartialEq)]
pub struct Genlmsghdr2<C, H, T> {
    /// Generic netlink message command
    pub cmd: C,
    /// Version of generic netlink family protocol
    pub version: u8,
    reserved: u16,
    pub user_header: H,
    /// Attributes included in generic netlink message
    attrs: GenlBuffer<T, Buffer>,
}

impl<C, T> Nl for Genlmsghdr<C, NoUserHeader, T>
where
    C: Cmd,
    T: NlAttrType,
{
    ...
}

impl<C, H, T> Nl for Genlmsghdr<C, UserHeader<H>, T>
where
    C: Cmd,
    H: Nl,
    T: NlAttrType,
{
    ...
}
```

How does that sound?

**Comment by chrboe** [comment]
Purely from looking at the source code, it would seem like the [`Hdrsize` controller attribute](https://github.com/jbaublitz/neli/blob/main/src/consts/genl.rs#L56) indicates the size of the user specific header for a family. I would guess that this gets set to 0 when the family has no user specific header.

**Comment by jbaublitz** [comment]
That may be hard to implement from a parsing standpoint given that to get to the right offset for the attributes, I need to know the size of the user specific header. It appears that even in `libnl`, getting the attributes requires [specifying a user header length](https://www.infradead.org/~tgr/libnl/doc/api/group__genl.html#ga800671a530b4c7a6fca7b5b43c8ca5aa). For now, I'll take the type approach that I outlined above. Any objections to that?

**Comment by chrboe** [comment]
Yep, `libnl` passes around the user header length all over the place.

The type-based approach looks fine to me :+1:

**Comment by jbaublitz** [comment]
Great! I'll start on this ASAP!

**Comment by jbaublitz** [comment]
@chrboe Hey! This is my next feature that I'm working on. I understand since it's been literal years, you may have moved on but I'd love to have you test it or tell me how I can test it for future users. Is there an existing netlink family that uses this?
