### ISSUE TITLE
Consider using bitflags crate in place of impl_flags macro and FlagBuffer

### ISSUE THREAD

**Issue by joshtriplett** [jbaublitz/neli#107]
It doesn't seem necessary to store flags in a Vec and bitwise-or them together when serializing. Flags could be stored as bitflags all the time.

It might be possible to switch to the bitflags crate rather than reimplementing a bitflags mechanism. That would also provide additional convenience methods, such as converting between the bitflags wrapper type and the underlying numeric type.

Enough of the implementation details of `impl_flags!` are hidden that it *might* be possible to do this without breaking backwards compatibility.

**Comment by jbaublitz** [comment]
Hi @joshtriplett! I actually have looked into the bitflags crate, but because you can only use the bitflags macro for integer types, this doesn't work very well with my enum approach. Obviously if I'm missing something, I'm open to reconsidering, but in the documentation it states:

> The flags should only be defined for integer types, otherwise unexpected type errors may occur at compile time.

If there's a clever way to get around this, I'm open to discussing, but if there isn't, I think having a statically-sized slice that has as many elements as there are bits in the integer representation is the best that I can do. Can you elaborate a little bit more on how you see this being implemented without sacrificing the enum approach for the flags?

**Comment by joshtriplett** [comment]
@jbaublitz I'm not suggesting that all enums can use bitflags, only those whose values are designed to work as flags and get bitwise ored together. Those could be defined as bitflags of the appropriate size, and that would give you all the desired operators. bitflags also handles the case of values that aren't specified, which it can still store and return as raw bits.

**Comment by jbaublitz** [comment]
@joshtriplett As discussed on Zulip, I'll investigate switching only the bitflag types over to `bitflags` and leaving the constants as-is.

**Comment by jbaublitz** [comment]
This is closed in #182!

**Comment by jbaublitz** [comment]
Whoops! This should stay open until that's merged.
