### ISSUE TITLE
Expand the tokio functionality

### ISSUE THREAD

**Issue by jbaublitz** [jbaublitz/neli#147]
**Would adding this feature cause a breaking change?**
Yes

Currently, tokio support primarily targets multicast groups with the `Stream` trait. Provide some additional convenience methods just like in `NlSocketHandle`.

**Comment by isomer** [comment]
Since you asked for opinions:

1) If neli::{NlSocket,NlSocketHandle} share a function in common with neli::tokio::NlSocket, they should ideally have the same function signature and do the same thing (modulo asyncronous behaviour).   This is because examples (both here, and found elsewhere) are often using the blocking API, and it makes it easier to adapt to your program if they work the same way but async.   I realise this isn't always possible, but it should be a general goal and any differences should be called out in the documentation with examples of how you would map between them.

2) One reason to use async is to have multiple tasks talking to the socket and doing different things at once.

I have many tasks that perform operations, they build and send messages onto the socket, and update a map that maps (pid,seq) to a mpsc channel.  I then have a single listener task that continuously reads messages off the socket, figures out which (pid,seq) it is a reply to, and forwards it over the associated mpsc (closing the mpsc and cleaning up the map if this is the last message).  For multicast events, I send them over a separate broadcast channel that tasks can subscribe to if they want those events.

2.a.i) To make things Send+Sync, I originally had them wrapped in a Arc<Mutex<>>, but this meant that the task blocking on recv() held the mutex and no messages could be sent.  For TCP sockets, this is solved by https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html#method.split, which neli doesn't support.  I emulated it by getting the raw socket and calling ::libc::dup() on the   socket.  (I needed the raw socket to get the pid anyway).  

2.a.ii) Another (better?) way, is that datagram sockets are naturally Send+Sync (any thread can read or write to an fd at any time without disrupting each other, and you obviously can move fd's around between threads (or even processes!)), and then implementing ready() / is_readable() / is_ writeable(). (https://docs.rs/tokio/latest/tokio/net/struct.UnixDatagram.html#method.ready and friends).   Then implementing Clone, or requiring users to use Arc<> or whatever.

2.b) It would be useful if the various Nlmsghdr / Genlmsghdr and related datastructures were Clone to make tokio::sync::broadcast work properly (currently I have to parse and convert them into my own internal event format which implements Clone).  I don't think there is any reason they can't be Clone (other than <C,T> having to also implement Clone.)

2.c) neli could subsume this entire thing, and implement it's own multithreaded "reply routing" and event broadcasting system (which will need the above to implement).  (Not necessarily as part of the NlSocket type).

3) Not really a tokio thing, but the neli_enum() macro is really useful for writing general networking stuff.  Have you considered extracting that into it's own crate?

4) Again, not really tokio, but while I'm here, it would be nice if you could define attribute enums that have the contents in them.  eg:

```rust
#[neli::neli_attribute(u32)]
enum FooAttribute {
  IfName(CString) => 1,
  IfIndex(i32) => 2,
  OperState(IfState) => 3,
  ...
}
```

and have neli do all the parsing and conversions backwards and forwards for those attributes in an even more type safe manner.

4.b) Again, not really tokio, and I've not really settled on how best to do this, but I've been experimenting with different variations of converting some of the messages to/from a struct (that's filled with Option<> for each possible attribute for that message).  Possibly with the command then having a way of saying "this command takes a struct of type X and returns a struct of type Y".

eg:
```rust
struct IfInfo {
 if_name: Option<String>,
 if_index: Option<i32>,
 if_state: Option<IfState>,
}

struct GetIfInfo;
impl NetlinkMessage for GetIfInfo {
  type InputMessage = struct IfInfo;
  type OutputMessage = struct IfInfo;
  type CommandType = NlInterfaceCmd;
  const Command = NlInterfaceCmd::GetIfInfo;
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
 ....
 let ret : IfInfo = netlink->send_and_wait(GetIfInfo, IfInfo { if_index: Some(1), .. default() }).await?;
 println!("Got: {:?}", ret);
}
```

That's off the top of my head, and I must sleep now, I'll try and think some more this weekend and see if I can add anything else.

**Comment by jbaublitz** [comment]
@isomer I'm sorry I never replied to this! I'm probably going to target this for 0.8.0 because as you can see from #182, there's already so much going into 0.7.0.

**Comment by jbaublitz** [comment]
> Since you asked for opinions:
> 
>     1. If neli::{NlSocket,NlSocketHandle} share a function in common with neli::tokio::NlSocket, they should ideally have the same function signature and do the same thing (modulo asyncronous behaviour).   This is because examples (both here, and found elsewhere) are often using the blocking API, and it makes it easier to adapt to your program if they work the same way but async.   I realise this isn't always possible, but it should be a general goal and any differences should be called out in the documentation with examples of how you would map between them.

See #20 for more information (I've tagged you there too), but I think I have an idea for a rework of NlSocketHandle that might meet this requirement.

> 
>     2. One reason to use async is to have multiple tasks talking to the socket and doing different things at once.
> 
> 
> I have many tasks that perform operations, they build and send messages onto the socket, and update a map that maps (pid,seq) to a mpsc channel. I then have a single listener task that continuously reads messages off the socket, figures out which (pid,seq) it is a reply to, and forwards it over the associated mpsc (closing the mpsc and cleaning up the map if this is the last message). For multicast events, I send them over a separate broadcast channel that tasks can subscribe to if they want those events.
> 
> 2.a.i) To make things Send+Sync, I originally had them wrapped in a Arc<Mutex<>>, but this meant that the task blocking on recv() held the mutex and no messages could be sent. For TCP sockets, this is solved by https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html#method.split, which neli doesn't support. I emulated it by getting the raw socket and calling ::libc::dup() on the socket. (I needed the raw socket to get the pid anyway).

In my redesign, I'd like to make all methods take `&self` which should allow you to simply wrap it in an `Arc<_>`. Would this be satisfactory for you?

> 
> 2.a.ii) Another (better?) way, is that datagram sockets are naturally Send+Sync (any thread can read or write to an fd at any time without disrupting each other, and you obviously can move fd's around between threads (or even processes!)), and then implementing ready() / is_readable() / is_ writeable(). (https://docs.rs/tokio/latest/tokio/net/struct.UnixDatagram.html#method.ready and friends). Then implementing Clone, or requiring users to use Arc<> or whatever.
> 
> 2.b) It would be useful if the various Nlmsghdr / Genlmsghdr and related datastructures were Clone to make tokio::sync::broadcast work properly (currently I have to parse and convert them into my own internal event format which implements Clone). I don't think there is any reason they can't be Clone (other than <C,T> having to also implement Clone.)

This should be resolved in 0.7.0 by #182. Submit anything I've missed that you need in terms of `Clone` implementations there.

> 
> 2.c) neli could subsume this entire thing, and implement it's own multithreaded "reply routing" and event broadcasting system (which will need the above to implement). (Not necessarily as part of the NlSocket type).

Per your suggestion, this is exactly what I'd like to do on top of `NlSocketHandle` and `tokio::NlSocket` as I've described in #20. 

> 
>     3. Not really a tokio thing, but the neli_enum() macro is really useful for writing general networking stuff.  Have you considered extracting that into it's own crate?

I'd consider that for sure if you'd like to use it independently! Please file a separate issue for that.

> 
>     4. Again, not really tokio, but while I'm here, it would be nice if you could define attribute enums that have the contents in them.  eg:
> 
> 
> ```rust
> #[neli::neli_attribute(u32)]
> enum FooAttribute {
>   IfName(CString) => 1,
>   IfIndex(i32) => 2,
>   OperState(IfState) => 3,
>   ...
> }
> ```
> 
> and have neli do all the parsing and conversions backwards and forwards for those attributes in an even more type safe manner.

Could you put up a separate issue for this? I think it's doable after looking briefly but we'd have to do a lot of looking at kernel code to appropriately type everything. Would you be willing to help with that?

> 
> 4.b) Again, not really tokio, and I've not really settled on how best to do this, but I've been experimenting with different variations of converting some of the messages to/from a struct (that's filled with Option<> for each possible attribute for that message). Possibly with the command then having a way of saying "this command takes a struct of type X and returns a struct of type Y".
> 
> eg:
> 
> ```rust
> struct IfInfo {
>  if_name: Option<String>,
>  if_index: Option<i32>,
>  if_state: Option<IfState>,
> }
> 
> struct GetIfInfo;
> impl NetlinkMessage for GetIfInfo {
>   type InputMessage = struct IfInfo;
>   type OutputMessage = struct IfInfo;
>   type CommandType = NlInterfaceCmd;
>   const Command = NlInterfaceCmd::GetIfInfo;
> }
> 
> fn main() -> Result<(), Box<dyn std::error::Error>> {
>  ....
>  let ret : IfInfo = netlink->send_and_wait(GetIfInfo, IfInfo { if_index: Some(1), .. default() }).await?;
>  println!("Got: {:?}", ret);
> }
> ```
> 
> That's off the top of my head, and I must sleep now, I'll try and think some more this weekend and see if I can add anything else.

I think this is addressed in #182. I'm actually autogenerating builders as of 0.7.0. Please feel free to provide any feedback on that PR because it is more verbose in some ways, but I think it's a net positive in terms of type safety and backwards compatibility.

**Comment by DCNick3** [comment]
> 3. Not really a tokio thing, but the neli_enum() macro is really useful for writing general networking stuff. 

You can take a loot at [num_enum](https://docs.rs/num_enum/latest/num_enum/) crate which seems to have similar functionality

**Comment by isomer** [comment]
> In my redesign, I'd like to make all methods take &self which should allow you to simply wrap it in an Arc<_>. Would this be satisfactory for you?

As long as it's possible to call recv() in one thread/task, and call send() in another without waiting for the recv() to complete.

> @isomer Do you have a good way of sorting out which messages are being sent to which multicast group? Or would you prefer a single receiver for all multicast messages in the routing functionality?

To be fair, what I've done so far is approximately (This is a pseudocode sketch, I've elided all the error checking/type handling/etc stuff to make this clearer):
```rust
  // chanmap is approximately HashMap<seqid, tokio::sync::mpsc>
  // broadcastchan is tokio::sync::broadcast::Sender
  if msg.nl_seq != 0 && msg.nl_pid == pid {
     let rpcchan = if more_messages_expected(&msg) {
        chanmap.get(&msg.nl_seq)
     } else {
        chanmap.remove(&msg.nl_seq)
     }
     rpcchan.send(buf.clone());
  }
  broadcastchan.send(buf);
```

ie, I don't really handle multicast at all, except to just broadcast it (like I do to all events I receive).

I use this for watching interfaces come/go/up/down (either by someone else on the system changing their state, or my program causing the state to change).  I also use it to receive 802.11 frames that the kernel is passing to userspace for handling.

In my code I end up with only one task listening for events for each type of netlink socket (rt or 802.11), but this is mostly just how things have ended up rather than being intentionally designed this way.  In theory this supports having multiple functions listening for events on seperate `tokio::sync::broadcast::Reciever`s, but I've not ended up using that functionality (at least not yet).

I'm pretty sure you can tell if a message is multicast, and which multicast group it's part of by calling recvmsg(2) (or recvfrom(2) which might be easier in rust as wrapping recvmsg is always a pain) and looking at the `sockaddr_nl` you get as the source address.

**Comment by jbaublitz** [comment]
> > In my redesign, I'd like to make all methods take &self which should allow you to simply wrap it in an Arc<_>. Would this be satisfactory for you?
> 
> As long as it's possible to call recv() in one thread/task, and call send() in another without waiting for the recv() to complete.

Yes, this is possible with the new design.

> 
> > @isomer Do you have a good way of sorting out which messages are being sent to which multicast group? Or would you prefer a single receiver for all multicast messages in the routing functionality?
> 
> To be fair, what I've done so far is approximately (This is a pseudocode sketch, I've elided all the error checking/type handling/etc stuff to make this clearer):
> 
> ```rust
>   // chanmap is approximately HashMap<seqid, tokio::sync::mpsc>
>   // broadcastchan is tokio::sync::broadcast::Sender
>   if msg.nl_seq != 0 && msg.nl_pid == pid {
>      let rpcchan = if more_messages_expected(&msg) {
>         chanmap.get(&msg.nl_seq)
>      } else {
>         chanmap.remove(&msg.nl_seq)
>      }
>      rpcchan.send(buf.clone());
>   }
>   broadcastchan.send(buf);
> ```
> 
> ie, I don't really handle multicast at all, except to just broadcast it (like I do to all events I receive).
> 
> I use this for watching interfaces come/go/up/down (either by someone else on the system changing their state, or my program causing the state to change). I also use it to receive 802.11 frames that the kernel is passing to userspace for handling.
> 
> In my code I end up with only one task listening for events for each type of netlink socket (rt or 802.11), but this is mostly just how things have ended up rather than being intentionally designed this way. In theory this supports having multiple functions listening for events on seperate `tokio::sync::broadcast::Reciever`s, but I've not ended up using that functionality (at least not yet).
> 
> I'm pretty sure you can tell if a message is multicast, and which multicast group it's part of by calling recvmsg(2) (or recvfrom(2) which might be easier in rust as wrapping recvmsg is always a pain) and looking at the `sockaddr_nl` you get as the source address.

Does `recvfrom()` fill in just the one multicast group that it's being sent from?

**Comment by jbaublitz** [comment]
@isomer Take a look at v0.7.0-rc1 and let me know if you have any feedback.

**Comment by isomer** [comment]
I believe that Linux only supports a message going to a single multicast group, so yes, `recvfrom()`s should only have the single multicast group.

I looked a bit at https://github.com/jbaublitz/neli/blob/v0.7.0-dev

this seems bigger than a 0.6 to 0.7 jump.  It's going to require a lot of rewriting code.  It would be good if there was a porting guide from 0.6 to 0.7, I think most of the changes are fairly straight forward and procedural.

Looking at https://github.com/jbaublitz/neli/blob/v0.7.0-dev/examples/genl_stream.rs#L32 makes me wonder if the type there should be part of the multicast object (possibly as a phantom type).  I can imagine screwing up and using the wrong type (or mixing up two different multicast streams) and being very confused.  Similar for NlRouter::send<> which has a lot of type parameters :)

To properly form some opinions I'm going to have to migrate one of my neli code bases to the new API and see what works well and what's hard.

**Comment by jbaublitz** [comment]
> I believe that Linux only supports a message going to a single multicast group, so yes, `recvfrom()`s should only have the single multicast group.
> 
> I looked a bit at https://github.com/jbaublitz/neli/blob/v0.7.0-dev
> 
> this seems bigger than a 0.6 to 0.7 jump. It's going to require a lot of rewriting code. It would be good if there was a porting guide from 0.6 to 0.7, I think most of the changes are fairly straight forward and procedural.

There actually is a migration guide in the changelog.

> 
> Looking at https://github.com/jbaublitz/neli/blob/v0.7.0-dev/examples/genl_stream.rs#L32 makes me wonder if the type there should be part of the multicast object (possibly as a phantom type). I can imagine screwing up and using the wrong type (or mixing up two different multicast streams) and being very confused. Similar for NlRouter::send<> which has a lot of type parameters :)

There is a single multicast stream for all multicast messages which is why it uses integer types for right now. I'm happy to put up an issue to split it out into multiple multicast streams for 0.7.0 if that would be preferable.

> 
> To properly form some opinions I'm going to have to migrate one of my neli code bases to the new API and see what works well and what's hard.

**Comment by isomer** [comment]
Okay, I've finally got some time to perform a full migration.  In general I think this is a good change, here's my stream of thought process as I do the mechanical part of the migration.

 - lots of fields are now accessors.  (not mentioned in the migration guide)  Several places things have changed from T to &T needing extra * to be sprinkled around.  nbd.
 - `&[Nlm::Request, Nlm::Ack]` doesn't compile, presumably due to the migration to `bitsets!`, which seems nice, but, an example of the mechanical transform would be helpful here.  The obvious `Nlm::Request|Nlm::Ack` doesn't work and the compiler error gives you no hint what to do next (it's `Nlm::REQUEST | Nlm::ACK`)
 - Nlattr::new(...) doesn't compile, presumably due to the migration to the builder pattern.  The docs (https://docs.rs/neli/0.7.0-rc1/neli/genl/struct.Nlattr.html) give no clue as to how to use this.  My "discovery" that I needed a `NlattrBuilder`, so my next attempt was `NlattrBuilder::default().nla_type(CtrlAttr::FamilyName).nla_payload(name).build().unwrap()` didn't work.  The final result was: ```NlattrBuilder::default().nla_type(AttrTypeBuilder::default().nla_type(CtrlAttr::FamilyName).build().unwrap()).nla_payload(name).build().unwrap()``` which is a bit ugly and verbose.  But I guess nicer than the long list of mysterious and easy to confuse "false"s.  It would be nice if the docstrings mention the name of the associated builder.
 - What happened to `neli::err::NlError`?  It's not documented in the migration guide. It looks like it was a "Yeah this shouldn't exist", which is probably true but now I'm trying to figure out how to rearchitect code (rather than just mechanical changes).  I've got several functions that return a `Result<_, NlError>` that I need to audit to see what they should be returning.  Probably the right thing to do, but a bit of work.

My wifi stuff is broken up into several subcrates, so I need to migrate my "netlink base" crate before I can even compile the higher level crates.  I suspect the entire crate should go away and be replaced with the more modern tokio work you've done but that's less mechanical ;)  First I would like to get things to compile, then I'll make more structural improvement (assuming it's possible, I might have to just replace this and make the more complex changes now).

It's unfortunately late here, so I'll continue later, so this is my first pass of notes.

**Comment by isomer** [comment]
Ah, and the next one is that `x.get_attr_handle()` →`x.attrs().get_attr_handle()`.

And `NlError` appears to have just become `SocketError`.

The new builder pattern means I can't pattern match on messages anymore because their internals are private:
```
  match msg {
                  Some(Ok(Nlmsghdr {
                      nl_payload: NlPayload::Payload(p),
                      .. 
                  })) => self.handle_payload(p),
                Some(Ok(Nlmsghdr {
                    nl_payload: NlPayload::Err(e),
                      ..
                })) => return Err(e.into());
                Some(Ok(_)) => {/* Ignore */}
                Some(Err(e)) => return Err(e.into()),
                None => break,
  }
```

**Comment by isomer** [comment]
Hrm, now I'm stuck.  I often take the Nlmsghdr, then extract out the payload, but I can't move the payload out nor can I clone it, I must take a reference.  This makes having a function that returns the payload hard because I now must make sure that the Nlmsghdr sticks around long enough to meet the references lifetime.

I can't pattern match to extract at the payload, I _can_ use `Nlmsghdr.get_err()` to extract the error, but `Nlmsghdr.get_payload()` returns a reference to the payload, so I can't use that either.  So now I'm kinda stuck and need to redesign/rewrite all of this.  Hmm.

**Comment by isomer** [comment]
`v0.7.0-rc1` is missing the "rt" feature for tokio (it's only part of dev-dependencies), so `tokio::spawn` doesn't exist which means the "tokio" feature of neli fails to compile from outside of the neli crate.

**Comment by jbaublitz** [comment]
I'm going to put up a PR for 0.7.0-r2 for your review.

**Comment by isomer** [comment]
nit: `resolve_genl_family()` returns a `Result<u16,_>`, but `send` requires a `NlType` as it's first argument.  Could `resolve_genl_family()` instead return a `Result<GenlId,_>`?   This keeps everything type safe and makes it less likely I'm going to screw up and use the wrong u16 :)

It might be useful to document that the second tuple member returned from  `neli::router::*::NlRouter::connect()` is the multicast group listen address.  

nit: It would be good if the builder deriver described what the default for each field was in the docstrings instead of having to check the source to see if I need to override a value.

I've managed to get my hostapd rewrite ported to the new version.  I ran into some of my own bugs (I spent ages trying to debug why stuff wasn't working, I was constructing my rtnl netlink object with the `NlFamily::Generic` which took for ages for me to notice, duh idiot me.  One thing I did here while debugging was change the initialisation of Nlrouter.seq so that it started at 10 instead of 0 to make it a bit easier to see what was going on when debugging with strace).

I eventually ripped out my netlink dispatcher and replaced it with NlRouter, which works very nicely.   

Losing the ability to pattern match, and nta_payload returning a reference required quite a bit of restructuring of code were probably the biggest changes.

Thanks for -rc2, I'll pull the changes tomorrow and check everything still works.
