### ISSUE TITLE
What makes the first variant of enums valid as defaults?

### ISSUE THREAD

**Issue by faern** [jbaublitz/neli#2]
I see that with the help of the macro `impl_var` you make the first variant of each enum the default variant: https://github.com/jbaublitz/neli/blob/master/src/ffi.rs#L24.

What makes the first variant a correct representation of the default value for that type? For example `NlFamily::Route` becomes the default value for `NlFamily`. For many of these enums I don't see why they should have a default.

**Comment by jbaublitz** [comment]
@faern So `Default` is mainly there for historical reasons (at one point I was playing around with procedural macros before I realized that netlink was not consistent enough to have macros cover the use cases I wanted the majority of the time without manually implementing some cases). The more I look at it, the more I realize that if it stays (which I'm not convinced it should), `UnrecognizedVariant` should be the default variant as I agree there is no sane way to determine a default for the enums representing constants. Just as a point of clarification, I added in the `UnrecognizedVariant` variant after I added default for a similar reason and I think that also bears some scrutiny. I was thinking anyway of using that to wrap the raw integer value so that it can still be accessed if I don't define one of the many required netlink constants but someone still needs to deserialize it for the time being until they open an issue or file a PR. I will play around with this and the issue with `Default` and see if I can find a better way of doing both of these things.

**Comment by faern** [comment]
Then I personally prefer no `Default` over a default that is always pointing to an "invalid" variant. Does not sound very useful in practice.

Are you sure you want to deserialize invalid values to `UnrecognizedVariant`? It sounds to me like the deserialization should fail and return an error instead. Would probably be much more convenient to handle using `?` etc than having to manually match and see if the deserialization ended up in the invalid variant.

**Comment by faern** [comment]
Previously when I have been dealing with converting integers into enums I have not implemented
`From<$ty> for $enum_type`, since that is infallible, and there are invalid values that can be inserted. Instead I usually add a method 
```rust
pub fn from_raw(raw: u32) -> Option<MyEnum>
```
Or maybe `Result` instead of `Option` and have it always be some `ErrorKind::InvalidValue` or similar.

**Comment by jbaublitz** [comment]
My concern with that is mainly because of the ability to define custom netlink families with IDs that are not able to be parsed as well as standard IDs in responses that do not seem to be documented or available in the headers. I added in the variant because of specific behavior I was getting from the ACPI bus in my project `pwrsurge`. The ID of the value for the netlink type in the response was not recognized and I am still unsure of what it signifies as it is not defined in any of the netlink C headers and even when I used [nltrace](https://github.com/socketpair/nltrace), it did not seem to recognize the resulting value either. Given that netlink sometimes has hard-to-predict behavior around certain IDs without looking at kernel code to see what it signifies, I wanted to be able to flag that this may or may not be an error and moving forward, I think it would be good to allow the user to inspect this value instead of utilizing a unit variant here as I'm doing as that swallows the actual numeric value that the user may or may not understand in that context.

**Comment by faern** [comment]
Ah, valid point to support values we don't know about indeed. But maybe that could be limited to only the enums where it's applicable, or can there be unknown constants coming out of all of the ones using `impl_var!`?

**Comment by jbaublitz** [comment]
From what I've seen digging through the kernel code, even attribute type in the `nlattr` struct can sometimes signify a list index in the case of a list of nested attributes or a legitimate type that is defined in headers. I think to really make it clear to the user, it is important to have a fallback in all cases as netlink is one of the more C-driven protocols I've seen. I had to pop open the kernel code multiple times to see exactly how messages were being constructed as there was very little technical documentation to understand the gotcha-type details. To move that to a typesafe framework, it's important to allow visibility into the C protocol way of doing things when you are unable to account for all of the possible variants that you may come across. I'd rather err on the side of caution and if the user doesn't encounter unrecognized results, then no harm is done, but if they do, it will make debugging significantly easier as this project matures.

**Comment by jbaublitz** [comment]
I have updated with a no-default-needed way of doing things. Closing.
