### ISSUE TITLE
Rework high-level NlSocketHandle API and potentially add a higher level API on top

### ISSUE THREAD

**Issue by jbaublitz** [jbaublitz/neli#20]
I am considering implementing higher level structs with some provided convenience functions:
* `NetlinkStream`
* `NetlinkSession`

Most of the work is already in place to make `NetlinkStream` work as it would simply receive and parse netlink messages as they become ready on the socket.

`NetlinkSession` would take a little more redesigning to enable tracking sequence numbers and netlink socket PIDs.

Open to any feedback as I know some people wanted a higher level API.

**Comment by jbaublitz** [comment]
I'm beginning work on this issue in the `v0.5.0-dev` branch.

**Comment by jbaublitz** [comment]
Work started in branch `v0.5.0-dev`.

**Comment by jbaublitz** [comment]
@isomer You've previously provided some incredibly helpful feedback around how you're using neli in the context of both multicast groups and request-reponse workflows. This is exactly what I want to target with this issue. This issue is related to #147 and whatever API I come up with for `NlSocketHandle` I want to match in `tokio::NlSocket`. My best idea that I can come up with is reworking `NlSocketHandle` and building a routing/broadcast layer on top of it.

* `NlSocketHandle`
The proposed changes are:
* Remove ACK handling in iteration and move this to the routing/broadcast layer. Currently if two requests are sent one after the other using the same socket, ACK handling breaks which is not good. I'd rather handle this at a layer that is PID/SEQ number aware. (cc @joshtriplett) Perhaps a compromise would be continue to provide iteration in `NlSocketHandle` but simply remove the ACK handling and instead pass the ACK up to the higher level API for verification where it would not be visible.

* Add a pool of `MAX_NL_LENGTH`-sized buffers that is user-configurable for parallelized receives and a customizable memory footprint. This is similar to what the kernel does in certain contexts around memory management and because netlink is a datagram protocol, not having a large enough buffer to receive the entire packet will cause data loss. In the low level API, users can provide their own sized buffers. However, I don't want users to have to do this (and don't see an ergonomic way to accomplish this) in higher level APIs. This leads me to believe that perhaps a semaphore-guarded buffer pool will allow:
1. users to specify how many concurrent reads they want to allow with the tradeoff of a greater memory footprint.
2. messages to never be truncated.
3. built-in blocking when the pool is exhausted which could be swapped out for tokio's semaphore in the `async` equivalent.

` `NlSocketRouter`
As you proposed, @isomer, this would be a higher level API which in the async case, will spawn a thread that asynchronously reads off messages as they come in and routes them via channel to the correct PID/SEQ number pair (represented by a handle) which could then:
* perform ACK checks
* iterate over the messages received without including the ACK as it has alreaday been verified like `NlSocketHandle` does now

A broadcast channel for multicast groups could potentially also be implemented using broadcast channels provided by tokio and some other construct for the blocking, non-async variant.

I feel like this is a good jumping off point. What are your thoughts?

**Comment by isomer** [comment]
Ack Handling: I've not yet run into problems with ack handling (I think, I have seen some weird things I've not managed to track down, maybe it's this?).  But yes, it does seem that having ack handling at a higher layer would be useful.

Buffering: I'm often frustrated by APIs that ask me to make decisions that I have no good basis for.  For instance knowing how many buffers and for what sizes.  I dunno, it's gonna depend on the hardware and the load of the machine.  Ideally (although I must admit I never actually do this), you should be able to call recvmsg(MSG_PEEK | MSG_TRUNC) and have the kernel tell you how big the buffer should be for your next recvmsg(2).  I generally only have 1 buffer.  Since the broadcasts already require it to be Clone, it'll be copied when it's passed off to somewhere else.

1. I'm not sure that they need concurrent reads, you can just have one task reading things, and handing them off then looping back relatively quickly.  If I need to isolate things, I'd split them onto a separate socket, and thus separate dispatcher.

1. Having untruncated messages should always be the goal ;)  Using `MAX_NL_LENGTH` is probably the easiest way to deal with that.  A client of neli can't easily resolve this without neli's help.

1. Flow control is more interesting.
   1. Brodcast messages (`tokio::sync::broadcast`) causes receivers who can't keep up to get "Lagged" messages. 
      1. For something watching IfUp/IfDown style messages, this can trigger clients to rerequest a dump to bring themselves back into sync.
      1. For something watching 802.11 frames from the kernel, dropping frames isn't that disasterous, the client will eventually retransmit the request.
   1. A slow RPC client could cause everything to become slow, but most RPC clients are actually blocking for a reply/ack, and this shouldn't be slow.  They're unlikely to be doing significant processing between the send and the reply unless the entire tokio scheduler is congested/overwhelmed, at which point blocking is probably wise (rather than adding more work to an already overloaded scheduler).
