### ISSUE TITLE
Access ethtool interface using neli

### ISSUE THREAD

**Issue by cueo** [jbaublitz/neli#222]
**Is this a question about neli specifically? If so, please describe.**
I wish to use `neli` to access `ethtool` interface (specifically `ethtool -S <ifname>` command). I am wondering if `neli` in its current state can be used to do that.

I have written a sample program which attempts to use `neli` to interface and send and receive an [ethtool command](https://www.kernel.org/doc/html/latest/networking/ethtool-netlink.html) (specifically, the `ETHTOOL_MSG_STATS_GET` command). Here’s a small project which I pushed to GitHub: [ethtool](https://github.com/cueo/rustuff/tree/neli/ethtool).

However, I keep running into the error: "Error response received from netlink: No such file or directory (os error 2)” or "Operation not supported".

I’d appreciate any help whatsoever. Here's the [code](https://github.com/mmynk/rustuff/blob/neli/ethtool/src/ethtool.rs) in question. I’m fairly certain the way I'm constructing the attributes in not the right way to do so.

Finally, thanks a lot for creating this library. It was an amazing source of learning for me (both about netlink and Rust).

**Comment by jbaublitz** [comment]
Hi @cueo, after digging into this a bit, I'm almost 100% confident that this is a user error largely because the code I'm seeing doesn't match the documentation that I'm reading. For example, nowhere do I see a nested netlink attribute in your code which is specifically called out in the documentation you linked. I'm not myself familiar with ethtool's protocol, but I'd recommend reading up on nested attributes because you simply have added attributes to the generic netlink message. Likely you need some sort of container attribute with values that I'm not sure of and then inside that container attribute, you need to add a nested attribute with a struct of the format specified in the documentation. Another error that I just wanted to call out since I saw it is the value of `ETHTOOL_GENL_NAME`. On my system, that macro evaluates to a string, not to a `u8`. Hope this helps point you in the right direction!
