### ISSUE TITLE
IfaF is too small

### ISSUE THREAD

**Issue by the284** [jbaublitz/neli#246]
https://github.com/jbaublitz/neli/blob/e50030dd22b2ad5390eed97445dbcc016e6bcd25/src/consts/rtnl.rs#L385 is defined as a u8 but it should be a u32 https://man7.org/linux/man-pages/man7/rtnetlink.7.html

Without the wider width it's not possible to use IFA_F_NOPREFIXROUTE that has value 0x200.

Suggest switch to u32

**Comment by jbaublitz** [comment]
Hi @the284, the flag is used in [this data structure](https://github.com/torvalds/linux/blob/9852d85ec9d492ebef56dc5f229416c925758edc/include/uapi/linux/if_addr.h#L8-L14) as the field `ifa_flags`. If we increase the size of the flags, it will be rejected by the kernel in that case because it's expecting a u8, not a u32. Where else are you hoping to use this flag or are you hoping to use it in that data structure?

**Comment by the284** [comment]
ah, it looks like flags >255 have to get added as an attribute somehow: https://patchwork.ozlabs.org/project/netdev/patch/1389127588-20236-1-git-send-email-thaller@redhat.com/

**Comment by the284** [comment]
yep, closing this one. these extended flags need to be set as an attribute like so

```
Rtattr::new(
    None,
    Ifa::Flags,
    IFA_F_NOPREFIXROUTE,
)
```
