### ISSUE TITLE
A copy form this crate

### ISSUE THREAD

**Issue by LuoZijun** [jbaublitz/neli#34]
Hi, @jbaublitz .

I made some changes based on your code, I hope you won't mind.
Finally, thank you for your work, your code has brought me a lot of help.

https://github.com/ExodusVPN/exodus/tree/rewrite/crates/netlink

Why did I create a branch?
Because I want all the operations of netlink to share a single memory (Stack). There is no heap memory allocation throughout the process.

**Comment by jbaublitz** [comment]
I'm not entirely sure why you'd want stack-only allocation here. I have enabled stack buffer allocation in `neli` using the lower level API and the places where heap allocation is always used is for reasons specific to protection against data loss. Netlink has a lot of corner cases that can lead to message truncation and data loss unless you're completely sure of the exact size of the message size before the response is read. This is very unlikely as many message sizes are variable and depend on the specific hardware and software configuration. The only way to mitigate this is either buffers that when stack allocated can overflow the stack if the allowed process stack size is too small or it requires heap allocation. The former seems ill advised and not generally portable. The latter seems to only be a problem if heap allocation is not available which is rarely the case for user space code. I'm not sure what your requirements are, but exclusively stack allocated buffers for netlink seems error prone and like something that is better suited to C, particularly because Rust does optimizations when using vectors that can eliminate some of the memory allocations and frees that are done on the heap and ultimately reduce the overhead traditionally associated with heap allocation. Ultimately you know your use case better than I do, but I would strongly caution you against this approach unless you are absolutely positive that heap allocation is a bottleneck for your application.

**Comment by LuoZijun** [comment]
thank you for the explanation :)
