### ISSUE TITLE
Should NlSocket::send/recv return unsigned lengths?

### ISSUE THREAD

**Issue by vorner** [jbaublitz/neli#47]
Hello

I have noticed that the `NlSocket::recv` and `::send` (the raw/low-level ones) return the amount of data read or written as `ssize_t` (which is usually equivalent to `isize`). This mimics the low-level C API. However, negative values indicate errors and these are indicated as `Result` on the Rust side.

Would it be OK if I send a PR changing them to usize for a more idiomatic API? Should I aim at master or the 0.5-dev branch?

Thank you

**Comment by jbaublitz** [comment]
Hi @vorner, that was intentional and I'd prefer to leave it the way it is. Those are low level calls and as a result I want them to reflect the return value of the underlying calls directly. My rule of thumb tends to be if libc defines a return type in terms of a Rust data type (`u16`, `i32`, etc.), I will use that as this indicates to me that the data type will never change on different architectures/operating systems. However, if libc defines it in terms of a `type` statement, I will use the defined type alias as this guarantees that we will have the correct representation of the return value on any platform supported by libc. I understand wanting to make it unsigned, but that doesn't make sense here as the signed type is opaque and may not change but definitely could across platforms.

**Comment by jbaublitz** [comment]
Interesting! I looked into this a little more and apparently `size_t` is unsigned. If you want to submit a PR for that, I'd be willing to accept that change.

**Comment by vorner** [comment]
OK, I'll do that in few days.

By the way, while `usize` and `size_t` can technically be different types, they have about the same requirements ‒ large enough to be able to represent size of any allocable object on the platform. But I'll use `libc::size_t`.

Should I send it to the 0.5-dev branch, as this would be API-breaking change?
