### ISSUE TITLE
Unidirectional message support

### ISSUE THREAD

**Issue by vorner** [jbaublitz/neli#51]
Some protocols have message types that make sense to be sent only in one direction ‒ eg, in the NFLOG (#48), configuration commands are only sent from application to kernel, while packets are only sent from kernel to application.

However, the Nl trait requires both `serialize` and `deserialize` for them. So there's the choice between writing the implementation for the other direction without practical need, or putting `unimplemented` inside it, which can explode at runtime. Neither prevents the user of the library from trying to send a receive only message or vice versa ‒ which would be indeed very nice if it was detected during compilation.

I'm not sure if it's worth the effort, but I'll put the idea here, to discuss. Would it make sense to split the `Nl` trait into read and write halves (and having `Nl` as alias for both directions)? That would make it similar to what eg. serde does.

**Comment by jbaublitz** [comment]
I'm not sure this makes sense in the context of `neli`. I originally tried using `serde` in `neli` and I've also tried breaking up `Nl` into multiple traits and each time I've tried something like this, it hasn't worked very well because the number of traits ends up exploding and trait bounds get very complicated and hard to reason about. If your only concern is about panicking behavior with `unimplemented!()`, you can also have the unused method return an error so you can handle it at runtime.

**Comment by vorner** [comment]
Well, returning the error is going in the other direction that what I'd like. Anyway, OK, let's not go into the splitting too much.
