### ISSUE TITLE
Provide examples

### ISSUE THREAD

**Issue by kpcyrd** [jbaublitz/neli#7]
hey!

I've tried to setup NETLINK_ROUTE+RTMGRP_LINK to monitor interface changes, but I'm having trouble getting the library to work, could you provide some examples for neli in an `examples/` folder? :)

Thanks!

**Comment by jbaublitz** [comment]
@kpcyrd This is definitely a gap currently. If you need examples before the next release, please look at the netlink portion of my other projects, holy196 or pwrsurge as they both use neli for netlink communication. I will however keep this open to keep track of this for the next release. I've also looked through the documentation I have so far on docs.rs and need to give that some additional attention and detail.

**Comment by jbaublitz** [comment]
@kpcyrd Just wanted to update you. I did some testing this week on the next release to make sure that it is backwards compatible with the current release and will be adding examples over the course of the next week and will then release the next version on crates.io.

**Comment by jbaublitz** [comment]
@kpcyrd Could you give some specific areas that would be helpful for me to document?

Things I'm currently documenting in the examples directory:
1. Resolving generic netlink multicast group ids
2. Resolving generic netlink family ids
3. `Nl` trait and serializing/deserializing structs/enums that implement it
4. `tokio` support for `NlSocket`
5. `send`/`recv` vs. `send_nl`/`recv_nl`
6. Parsing netlink attributes using `get_attr_handle()`

If you need some working examples, what I currently do to monitor ACPI events is the following:
Resolve the multicast group:
https://github.com/jbaublitz/pwrsurge/blob/master/src/netlink.rs#L9-L13
Provide a parsing function for ACPI events that are returned from the kernel
https://github.com/jbaublitz/pwrsurge/blob/master/src/netlink.rs#L15-L18
Iterate over the socket events that are returned using `tokio`:
https://github.com/jbaublitz/pwrsurge/blob/master/src/event.rs#L70-L98

Let me know if you need any additional assistance. I will push the outlined stripped-down examples today and work on better high level documentation as well.

**Comment by jbaublitz** [comment]
@kpcyrd I may be able to help here. I dug into the kernel code for rtnetlink and it is notifying via multicast groups. In the interest of resolving this issue as efficiently as possible, can you answer a few questions before I dive in?

* Is the prototype you're working on public?
* Are you familiar with multicast groups in netlink and how those work?
* Have you taken a look at the documentation for `NlSocket::connect()` and its `group` parameter?

One note is I have not yet implemented rtnetlink structs so I will make a note to do so in neli before closing this issue so that you do not have to implement those. While you can do that and do an `impl Nl` and have everything work, that would be required of everyone using rtnetlink which is silly for me to have people do. It could be a temporary fix on your end for now though if you want to get this moving along before I put that in place.

Once I get that in place, my guess is all of the pieces are here for you to put this together and I'm happy to help along the way.

**Comment by kpcyrd** [comment]
> Is the prototype you're working on public?
> Are you familiar with multicast groups in netlink and how those work?
> Have you taken a look at the documentation for NlSocket::connect() and its group parameter?

I know very little about netlink or it's multicast groups. I've digged through the ifplugd code for a bit and it seems RTMGRP_LINK is the group I need.
```c
        if (nlapi_open(RTMGRP_LINK) < 0)
            goto finish;

[snip]

int nlapi_open(uint32_t groups) {
    struct sockaddr_nl addr;

    if ((nlapi_fd = socket(PF_NETLINK, SOCK_DGRAM, NETLINK_ROUTE)) < 0) {
        daemon_log(LOG_ERR, "socket(PF_NETLINK): %s\n", strerror(errno));
        return -1;
    }

    memset(&addr, 0, sizeof(addr));
    addr.nl_family = AF_NETLINK;
    addr.nl_groups = groups; // nl_groups is set to RTMGRP_LINK here
    addr.nl_pid = getpid();

    if (bind(nlapi_fd, (struct sockaddr *) &addr, sizeof(addr)) < 0) {
        close(nlapi_fd);
        daemon_log(LOG_ERR, "bind(): %s\n", strerror(errno));
        return -1;
    }

    return 0;
}
```

That should roughly translate to:
```rust
extern crate neli;

use neli::ffi::NlFamily;
use neli::ffi::CtrlCmd;
use neli::genlhdr::GenlHdr;
use neli::ffi::GenlId;
use neli::socket::NlSocket;

const RTMGRP_LINK: u32 = 1; // value on my system

fn main() {
    let my_pid = std::process::id();
    let socket = NlSocket::<GenlId, GenlHdr<CtrlCmd>>::connect(NlFamily::Route, Some(my_pid), vec![RTMGRP_LINK]).expect("connect");

    let msg = socket.recv_nl_typed(None).expect("recv");
    println!("{:?}", msg);
}
```

Assuming the code that is setting up the socket is correct, I can't get the receive to work.

> One note is I have not yet implemented rtnetlink structs so I will make a note to do so in neli before closing this issue so that you do not have to implement those.

This might be the point where I'm currently stuck. :)

**Comment by jbaublitz** [comment]
Ok, this is very helpful. I will dig around a bit and update the docs and provided structs for this. Once I've provided the necessary structs, I will post some example code here as well specific to what you're hoping to do.

**Comment by jbaublitz** [comment]
@kpcyrd Update: I have started working on the structs for rtnetlink. I needed to look into this portion of netlink and will hopefully have some results soon. Be advised that the next release will have a _lot_ of breaking changes around the module and struct naming to clean up some of my past sins.

**Comment by jbaublitz** [comment]
@kpcyrd I got pulled away from this project for a while but am back on it. You should see some additions here and potentially linked to [this issue](https://github.com/rust-lang/libc/issues/1059) in libc as I add to `rtnl.rs` in neli. Sorry for the long delay.

**Comment by mhristache** [comment]
the current api is very low level. do you have any plans to add a higher level api?

**Comment by jbaublitz** [comment]
Hi @mhristache, I sincerely apologize for the delay. There is a higher level API that is not currently documented with examples. It uses tokio to essentially process a stream of Netlink message structs. Is this the kind of higher level API to which you're referring?

If so, today my plan is to try to tackle some of the documentation so that my library is a bit more usable than it is today. Code should never be "self documenting".

**Comment by jbaublitz** [comment]
@kpcyrd `rtnl.rs` is slowly coming along. The delay is partially due to my laptop crashing and partly due to me needing to explore this subsystem of netlink so I do it right. Hopefully version 0.4.0 will be out within the next few weeks.

@mhristache I'd be really interested in your feedback if you'd be willing to open another issue for a higher level API and we can discuss there. That has been something I've been interested in solidifying eventually and would love your feedback here if you have ideas.

**Comment by mhristache** [comment]
@jbaublitz sorry for my late reply. I was on a long vacation. 
What I mean by a high level API is something similar to e.g. [pyroute2](https://github.com/svinota/pyroute2) lib, i.e. something that hides all the netlink complexity behind a nice and simple api. There are several other rust libs that are progressing in this space (they are nicely summarized [here](https://crates.io/crates/rtnetlink)). Most of these other projects are focusing on the iproute part of netlink while this project seems more generic. I am not sure a higher level api for `neli` is something to pursue.

**Comment by jbaublitz** [comment]
@mhristache I've considered it. I'm happy to discuss in more detail but I could envision something like a `NlSession` struct handling the top level netlink packets (things like the `seq` number, `pid`, etc.) at the very least and some more convenience functions. I've been wanting to rework the API significantly to be a little more user friendly for 0.5.0. Docs will be significantly better by 0.4.0. If this sounds like something you'd benefit from, please open another issue and let's definitely discuss this as it's been on my mind too.

**Comment by jbaublitz** [comment]
To anyone following along (I know, it's been a really long time and I apologize), I'm revamping the documentation piece by piece. There's an outstanding PR for providing documentation for constants that I'm going to wait for a few days to merge as I pulled the author's changes into a new branch and made some edits and want to give a chance for feedback. This is one step in making the documentation better. Also implementing the newly outlined strategy in the README. Thank you for your patience. Anyone looking for more immediate help in the meantime is welcome to open an issue and I will gladly walk you through your specific case until I can close this issue out.

**Comment by jbaublitz** [comment]
Some examples have been added to `neli` and they are tested in CI so any breaking changes to the API will cause tests to fail if the examples are not updated to work with the changes. I'm going to keep tracking documentation changes needed before `0.4.0` release in #8 but the example portion should be closed. Let me know if I should reopen but I'm going to close this out.
