### ISSUE TITLE
nla_type is incorrectly parsed for nested attributes

### ISSUE THREAD

**Issue by dhl** [jbaublitz/neli#84]
# Summary
`neli` parses `nla_type` incorrectly for nested attributes.

# Version
0.4.3

# Expected Behavior
Given a nested attribute with `nla_type` set to `1000000000001000b` (decimal 32776) in the message payload, `neli` should parse the `nla_type` as `0000000000001000b` (decimal 8).

# Actual Behavior
`neli` incorrectly parses attribute type `1000000000001000b` as `1000000000001000b`

# Description
The two most significant bits of the nla_type is used to denote if the attribute is nested (bit 0), and if the payload is in network byte order (bit 1).

Since these are meta data for the attribute, those bits should be masked out before setting the `nla_type` field in the `Nlattr` struct being parsed.

**Comment by gluxon** [comment]
Reference:

https://github.com/torvalds/linux/blob/90280eaa88ac1a9140dc759941123530d5545bb6/include/uapi/linux/netlink.h#L216-#L228

**Comment by jbaublitz** [comment]
I remember bumping into that documentation when writing the attribute handling code that I have. While this should definitely be considered a bug and be fixed, there are two reasons it's not there:
1. I think I meant to provide a way to exact those bits and the type itself separately at some point. That clearly never happened so thank you for reporting this.
2. The kernel subsystem I work in predominantly doesn't seem to set these bits so I never bumped into this during my testing. I'm not actively involved in kernel development so I'm unsure if this is a bug or an unrelated reason.

Either way, let's talk about fixing this. My initial idea for this is that we make an `NlaType` struct that has two boolean fields and then mask those two bits out for the type. Does this sound good to both of you? Do you have other ideas?

One note is that I'll merge this into master before my `v0.5.0-dev` branch because there are significant breaking changes to the API and I'd like to allow you to take advantage of the fix by pinning at that commit and then you can roll over to v0.5.0 as you have the time. Does that sound good?

**Comment by gluxon** [comment]
> While this should definitely be considered a bug and be fixed, there are two reasons it's not there

Thanks for explaining here! Bugs happen. 🙂

> Either way, let's talk about fixing this. My initial idea for this is that we make an NlaType struct that has two boolean fields and then mask those two bits out for the type. Does this sound good to both of you? Do you have other ideas?

Do you think those fields are useful to consumers of neli? (I'm not sure myself.) I can see the nested bit being useful, but I think it's worth noting that `netlink.h` chose to just mask out those bits in their implementation of [`nla_type()`](https://github.com/torvalds/linux/blob/29d9f30d4ce6c7a38745a54a8cddface10013490/include/net/netlink.h#L1063-L1066).

I would vote to do the same for a `v0.4.4` release so this doesn't produce a breaking change on the `v0.4.x` branch. That's my thought, but the decision is up to you of course.

> One note is that I'll merge this into master before my v0.5.0-dev branch because there are significant breaking changes to the API and I'd like to allow you to take advantage of the fix by pinning at that commit and then you can roll over to v0.5.0 as you have the time. Does that sound good?

That sounds good, but any chance we can get a `v0.4.4` release as well? I do think that would be helpful.

**Comment by jbaublitz** [comment]
> > While this should definitely be considered a bug and be fixed, there are two reasons it's not there
> 
> Thanks for explaining here! Bugs happen. slightly_smiling_face
> 
> > Either way, let's talk about fixing this. My initial idea for this is that we make an NlaType struct that has two boolean fields and then mask those two bits out for the type. Does this sound good to both of you? Do you have other ideas?
> 
> Do you think those fields are useful to consumers of neli? (I'm not sure myself.) I can see the nested bit being useful, but I think it's worth noting that `netlink.h` chose to just mask out those bits in their implementation of [`nla_type()`](https://github.com/torvalds/linux/blob/29d9f30d4ce6c7a38745a54a8cddface10013490/include/net/netlink.h#L1063-L1066).

I do think I need to include those bits but how I go about it is up for debate. It may also be reasonable to add those boolean fields at the `Nlattr` level as opposed to the `nla_type` level as that might be easier for a user to interact with. What do you think?

> 
> I would vote to do the same for a `v0.4.4` release so this doesn't produce a breaking change on the `v0.4.x` branch. That's my thought, but the decision is up to you of course.
> 

I'm happy to release a version of `v0.5.0-rc1` but I cannot release on the `v0.4.x` track because I've already merged breaking changes into master. This would a allow a released version on crates.io that would contain a minimal number of breaking changes. Does that sound good?

> > One note is that I'll merge this into master before my v0.5.0-dev branch because there are significant breaking changes to the API and I'd like to allow you to take advantage of the fix by pinning at that commit and then you can roll over to v0.5.0 as you have the time. Does that sound good?
> 
> That sounds good, but any chance we can get a `v0.4.4` release as well? I do think that would be helpful.

See above, but this seems like a strong argument for supporting minor version branches moving forward. For now, I think a release candidate before merging the very big breaking changes is the best I can do.

**Comment by gluxon** [comment]
> For now, I think a release candidate before merging the very big breaking changes is the best I can do.

Ah understood.

> I do think I need to include those bits but how I go about it is up for debate. It may also be reasonable to add those boolean fields at the Nlattr level as opposed to the nla_type level as that might be easier for a user to interact with. What do you think?

I do lean towards that. Although these bits are in nla_type, they're really attribute level information so it makes sense from that perspective. The downside of having these at the `Nlattr` level is that it deviates from the C implementation. I think that's fine but I'm not sure how you feel about that.

**Comment by jbaublitz** [comment]
> > For now, I think a release candidate before merging the very big breaking changes is the best I can do.
> 
> Ah understood.
> 
> > I do think I need to include those bits but how I go about it is up for debate. It may also be reasonable to add those boolean fields at the Nlattr level as opposed to the nla_type level as that might be easier for a user to interact with. What do you think?
> 
> I do lean towards that. Although these bits are in nla_type, they're really attribute level information so it makes sense from that perspective. The downside of having these at the `Nlattr` level is that it deviates from the C implementation. I think that's fine but I'm not sure how you feel about that.

I think that even though it deviates from the C implementation, it's more understandable as an abstraction so it would probably be more user friendly. I'll put up a PR, tag you both in it to test, and if it works for you, I'll cut a release candidate.

**Comment by dhl** [comment]
Thanks, @jbaublitz, for responding to this so quickly!

I agree with @gluxon that if we do want to keep the flags, `Nlattr` does seem like a better home than having them in `NlaType`.

Really grateful to the both of you for helping with this.

**Comment by jbaublitz** [comment]
`v0.5.0-rc1` is released.

**Comment by gluxon** [comment]
@jbaublitz Hey John, thanks for the patch. You may be interested in the source of this change, which I believe is this kernel patch last year.

https://github.com/torvalds/linux/commit/ae0be8de9a53cda3505865c11826d8ff0640237c

While applying the fix on https://github.com/gluxon/wireguard-uapi-rs I discovered that kernel versions after this patch require the `NLA_F_NESTED` set for messages sent. Just a heads up that it may not be enough to just mask away the bit on read.
