### ISSUE TITLE
"the trait `neli::consts::genl::Cmd` is not implemented" Problem with impl_var/impl_trait for custom types

### ISSUE THREAD

**Issue by phip1611** [jbaublitz/neli#99]
Hi,
first of all thanks for the great lib. I'm using 0.4.4 in an uni project and it works great. 
I wanted to update to 0.5.1 but **I'm struggeling with my custom types**. Maybe the macros `impl_trait!` and `impl_var!` doesn't work or the documentation is misleading?

I did for my custom type exactly what you did in `neli::consts::genl` for `CtrlCmd`. But in my case it always tells me `"the trait 'neli::consts::genl::Cmd' is not implemented"`. If I expand the macro, it looks like there is everything implemented..

This definetely worked in neli 0.4.4.

Minimal reproducible example
```rust
use neli::consts::genl::{CtrlCmd, Index};
use neli::genl::Genlmsghdr;
use neli::types::{GenlBuffer, Buffer};
neli::impl_trait!(
    /// Trait marking constants valid for use in
    /// [`Genlmsghdr`][crate::genl::Genlmsghdr] field, `cmd`.
    pub Cmd,
    u8,
    /// Wrapper valid for use with all values in the [`Genlmsghdr`]
    /// field, `cmd`
    MyCustumOperationConsts,
    MyCustumOperation
);

neli::impl_var!(
    /// Values for `cmd` in [`Genlmsghdr`][crate::genl::Genlmsghdr].
    pub MyCustumOperation, u8,
    Unspec => 0 as u8,
    Echo => 1 as u8
);

fn main() {
    // the trait `neli::consts::genl::Cmd` is not implemented for `MyCustumOperation`
    // but it works with CtrlCmd::Getfamily
    let attrs: GenlBuffer<Index, Buffer> = GenlBuffer::new();
    Genlmsghdr::new(
        // CtrlCmd::Getfamily,
        MyCustumOperation::Echo,
        1,
        attrs,
    );
}
```

In neli 0.4.4 it worked like this:
```rust
neli::impl_var_trait!(
    MyCustumOperation, u8, Cmd,
    Unspec => 0,
    Echo => 1
);

```

Am I doing something wrong or is there a problem with neli?

**Comment by phip1611** [comment]
Okay if I add `impl neli::consts::genl::Cmd for OveyOperation {}` after the `impl_trait` line it works. But is this intended?! Shouldn't this be done automatically?

**Comment by jbaublitz** [comment]
Hi @phip1611. Thanks for reporting this! The reason for this is that `impl_trait` has been changed to implement a custom wrapper type as referenced in the last code block of the [docs here](https://docs.rs/neli/0.5.1/neli/macro.impl_trait.html). I can see a few potential possibilities that may satisfy what you're looking for. One is that you can open a PR to add your constants upstream and then I can include it in the wrapper type. Another option is that I can modify the macro slightly to make `$wrapper_type` optional in the `impl_trait` macro so that you can still use that macro to implement the marker trait for your new constant enums. What would your preference here be? One small note that due to the limitations of the implementations of wrapper types, I cannot include your type in the packaged wrapper type for the `Cmd` trait unless you contribute it upstream. Let me know what your thoughts are!

**Comment by phip1611** [comment]
I think packaging custom types into neli is the wrong approach. This would result in never ending pull requests for new types... :)  There should be an easy way for everyone to declare their custom types inside their own crate/outside of neli. I think an adjustment to the macro would be the best option :) , i.e. that one is not longer forced to add `impl neli::consts::genl::Cmd for MyCustumOperation {}` additionally under the `impl_trait!` line.

To be honest I don't get the whole concept of the wrapper enums at all. What is exactly the purpose of for example `CmdConsts`, the wrapper type for `CtrlCmd`? It's not even used in a full text search, see https://github.com/jbaublitz/neli/search?q=CmdConsts 

I'd love to see an example in `repo: neli/examples/` on how to create custom enums for ".cmd"-field as well as custom netlink attributes. If you don't mind I create a PR to add this - maybe we can figure out a good solution that way.

**Comment by jbaublitz** [comment]
> I think packaging custom types into neli is the wrong approach.
If this is a custom netlink family (as it appears it is based on the issue you linked to), I agree that it might be best to leave it out of neli. I wasn't sure if you were looking to add support for an existing family.

> I think an adjustment to the macro would be the best option
I'm happy to put up a PR for this for you to test out and look over if you'd like!

> To be honest I don't get the whole concept of the wrapper enums at all. What is exactly the purpose of for example CmdConsts, the wrapper type for CtrlCmd? It's not even used in a full text search, see https://github.com/jbaublitz/neli/search?q=CmdConsts

The wrapper type is due to some of the inherent type unsafety in the netlink protocol. In the general case, you are not always guaranteed that you will get values from only one type of enum in a response. The wrapper types dynamically determine which enum the constant belongs to and wraps that in a top level type that can be used as a type parameter if the user does not know which type should be used to cover all cases. There is not really a good alternative in the context of wrapping constants in enums which I'm pretty solidly for because of the type safety it provides. If you are sure that in your workflow, you will only be receiving one type of enum in responses, you don't need this feature, but I have bumped into other places where it is necessary.

> I'd love to see an example in repo: neli/examples/ on how to create custom enums for ".cmd"-field as well as custom netlink attributes. If you don't mind I create a PR to add this - maybe we can figure out a good solution that way.

I can definitely add that but I'm not sure what you'd want beyond what I have in the documentation. Can you be specific about what you would want the example to include?

**Comment by phip1611** [comment]
@jbaublitz Yes I was talking about custom generic netlink families. Sorry, I should have said that. I think you are going to better understand the problem I want to address when you read the comments of the PR #103. 
I'd love to hear what you think.
